# Generated by Django 4.1.7 on 2023-03-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=10, unique=True, verbose_name="名字"),
                ),
                ("pub_data", models.DateField(null=True)),
                ("readcount", models.IntegerField(default=0)),
                ("commentcount", models.IntegerField(default=0)),
                ("is_delete", models.BooleanField(default=False)),
            ],
            options={"db_table": "bookinfo",},
        ),
        migrations.CreateModel(
            name="PeopleInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "male"), (1, "female")],
                        default=0,
                        verbose_name="性别",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, null=True, verbose_name="描述"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="逻辑删除")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.bookinfo",
                        verbose_name="书籍",
                    ),
                ),
            ],
            options={"verbose_name": "人物信息", "db_table": "peopleinfo",},
        ),
    ]
